name: eco_block
description: EcoBlock
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.0.0
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  flutter_mobile_vision: ^0.1.3
  fl_chart: ^0.20.1
  googleapis: any
  googleapis_auth: any
  firebase_ml_vision: ^0.11.0
  image_picker: 0.4.12+1
  firebase_core: "^1.0.2"
  cloud_firestore: "^1.0.3"
  flutter_spinkit: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - images/
